import React, { useState, useCallback } from "react";
import { useTranslation } from "react-i18next";
import { Page, Cell, Layout, Text } from "@wix/design-system";

import { useFetchRecoil } from "../../hooks/useFetch";

import { statisticsState } from "../../services/state";
import { fetchStatistics } from "../../services/api";

import { Stats } from "../../../interfaces";

export default function StatisticsTab() {
  const { t } = useTranslation();
  const [selectedFilterId, setSelectedFilterId] = useState(3);

  return (
    <Cell>
      <Layout>
        <Cell>
          <Page.Section
            title={t('statisticsTab.title', {defaultValue: "Statistics"})}
            subtitle={t('statisticsTab.subtitle', {defaultValue: "Monitor sales generated by the Quantity and Volume Discount app."})}
          />
        </Cell>
        <Cell>
          <Text>{t('statisticsTab.content', {defaultValue: "Statistics content goes here"})}</Text>
        </Cell>
      </Layout>
    </Cell>
  );
}
