import React, { useState, useCallback } from "react";
import { Page, Cell, Layout, Text } from "@wix/design-system";

import { useFetchRecoil } from "../../hooks/useFetch";

import { statisticsState } from "../../services/state";
import { fetchStatistics } from "../../services/api";

import { Stats } from "../../../interfaces";

export default function StatisticsTab() {
  const [selectedFilterId, setSelectedFilterId] = useState(3);

  return (
    <Cell>
      <Layout>
        <Cell>
          <Page.Section
            title="Statistics"
            subtitle="Monitor sales generated by the Quantity and Volume Discount app."
          />
        </Cell>
        <Cell>
          <Text>Statistics content goes here</Text>
        </Cell>
      </Layout>
    </Cell>
  );
}
