export const ALL_PRICING_PLANS = [
  {
    plan: "Free",
    credits_per_month: 20,
    monthly_price: "$0",
    per_month_billed_yearly: null,
    one_pay_yearly_price: null,
    your_cost: "$0.63",
    profit_vs_cost_monthly_yearly: null,
    user_gen_monthly: null,
  },
  {
    plan: "Basic",
    credits_per_month: 20,
    monthly_price: "$0",
    per_month_billed_yearly: null,
    one_pay_yearly_price: null,
    your_cost: "$0.63",
    profit_vs_cost_monthly_yearly: null,
    user_gen_monthly: null,
  },
  {
    plan: "Hobby",
    credits_per_month: 60,
    monthly_price: "$8.99",
    per_month_billed_yearly: "$6.99",
    one_pay_yearly_price: "$83.88",
    your_cost: "$2.52",
    profit_vs_cost_monthly_yearly: "+257% / +177%",
    user_gen_monthly: "$0.150",
  },
  {
    plan: "Pro",
    credits_per_month: 120,
    monthly_price: "$14.99",
    per_month_billed_yearly: "$11.99",
    one_pay_yearly_price: "$143.88",
    your_cost: "$5.04",
    profit_vs_cost_monthly_yearly: "+197% / +138%",
    user_gen_monthly: "$0.125",
  },
  {
    plan: "Expert",
    credits_per_month: 300,
    monthly_price: "$29.99",
    per_month_billed_yearly: "$24.99",
    one_pay_yearly_price: "$299.88",
    your_cost: "$12.60",
    profit_vs_cost_monthly_yearly: "+138% / +102%",
    user_gen_monthly: "$0.100",
  },
  {
    plan: "Premium500",
    credits_per_month: 500,
    monthly_price: "$49.99",
    per_month_billed_yearly: "$44.99",
    one_pay_yearly_price: "$539.88",
    your_cost: "$21.00",
    profit_vs_cost_monthly_yearly: "+138% / +114%",
    user_gen_monthly: "$0.100",
  },
  {
    plan: "Premium1200",
    credits_per_month: 1200,
    monthly_price: "$99.99",
    per_month_billed_yearly: "$94.99",
    one_pay_yearly_price: "$1139.88",
    your_cost: "$50.40",
    profit_vs_cost_monthly_yearly: "+98% / +88%",
    user_gen_monthly: "$0.083",
  },
  {
    plan: "Premium2400",
    credits_per_month: 2400,
    monthly_price: "$199.99",
    per_month_billed_yearly: "$189.99",
    one_pay_yearly_price: "$2279.88",
    your_cost: "$100.80",
    profit_vs_cost_monthly_yearly: "+98% / +88%",
    user_gen_monthly: "$0.083",
  },
  {
    plan: "Premium4800",
    credits_per_month: 4800,
    monthly_price: "$399.99",
    per_month_billed_yearly: "$379.99",
    one_pay_yearly_price: "$4559.88",
    your_cost: "$201.60",
    profit_vs_cost_monthly_yearly: "+98% / +88%",
    user_gen_monthly: "$0.083",
  },
];

export const ENTERPRISE_PLAN_NAMES = [
  "Premium500",
  "Premium1200",
  "Premium2400",
  "Premium4800",
];
